wrappid/wrappid-service

wrappid.conf.json

Remove prod and stage  from wrappid.conf.json
Ref: #15

feat: Enhancement wrappid config file

---

src/swagger-output.json
src/wrappidApp.js

setup  swagger  called with  wrappidApp, swaggerJsonFile and add  a basic swagger-output.json
Ref: #19

feat: setup  swagger  called with  wrappidApp, swaggerJsonFile

---

.eslintrc.js
package.json
src/modules/_system/controllers.registry.js
src/modules/_system/controllers/_system.controller.js
src/modules/_system/controllers/test.controller.js
src/modules/_system/functions.registry.js
src/modules/_system/functions/test.functions.js
src/modules/_system/middlewares.registry.js
src/modules/_system/middlewares/test.middleware.js
src/modules/_system/models.registry.js
src/modules/_system/models/TestDatas.model.js
src/modules/_system/tasks.registry.js
src/modules/_system/tasks/TestTask.js
src/registry/ControllersRegistry.js
src/registry/FunctionsRegistry.js
src/registry/MiddlewaresRegistry.js
src/registry/ModelsRegistry.js
src/registry/TasksRegistry.js
src/registry/ValidationsRegistry.js
src/registry/index.js
src/server.js
src/wrappidApp.js

Basic eslint rules add for express and javascript
Ref: #18

feat: Add basic eslint rules

---

package.json

add missing dependency @wrappid/service-core
Ref: #28

fix: :bug: add missing dependency

---

.github/pull_request_template.md
.github/workflows/pr-guardrails.yml
.husky/pre-commit
lint-staged.config.js
package-lock.json
package.json
src/wrappidApp.js

add PR GuardRails, husky and linting scripts
Ref: #23

ci(config): :wrench: add branch rules and code format rules

---

.husky/pre-commit
.vscode/settings.json
package-lock.json
package.json

update branch validation husky script
Ref: #23

ci(config): :wrench: modify husky script

---

.github/pull_request_template.md
.github/workflows/pr-guardrails.yml
.husky/pre-commit
.vscode/settings.json
lint-staged.config.js
package-lock.json
package.json
src/wrappidApp.js
wrappid.conf.json

Merge development branch into main branch

Merge development into main

---

package.json

add missing keys, author, license, in package.json
Ref: wrappid/wrappid-service #36

docs(config): : :memo: add missing keys in package.json

---

package.json
tsconfig.json

feat: build scripts added

---

.eslintrc.js
package-lock.json
package.json
src/modules/_system/controllers.registry.ts
src/modules/_system/controllers/test.controller.ts
src/modules/_system/functions/test.functions.ts
src/modules/_system/middlewares.registry.ts
src/modules/_system/tasks.registry.ts
src/registry/TasksRegistry.ts
src/wrappidApp.ts

code linting fix , updated eslintrc file and add packages
Ref: #42
---

refactor(global): :art: code linting fix

---

.eslintrc.js
package-lock.json
package.json
src/modules/_system/controllers.registry.ts
src/modules/_system/controllers/test.controller.ts
src/modules/_system/functions/test.functions.ts
src/modules/_system/middlewares.registry.ts
src/modules/_system/tasks.registry.ts
src/registry/TasksRegistry.ts
src/wrappidApp.ts

refactor: code linting fix

---

.eslintrc.js

import resolver settings in eslintrc file added for eslint import resolver
Ref #no-issue
---

fix(config): :fire: import resolver settings in eslintrc file

---

.github/pull_request_template.md
.github/workflows/pr-guardrails.yml

Update PR guardrail's code style script to only check for added and modified files only, and apply lint check
Ref: #51
---

fix(config): :bug: fix lint check on pr

---

package.json

ts-node start with nodemon
Ref: #56
---

feat: :sparkles: start with nodemon

---

package.json

merge: from Development

---

.github/workflows/create-release.yml.NOT_IN_USE
.github/workflows/create-tag.yml.NOT_IN_USE
.github/workflows/service-deploy.yml.NOT_IN_USE
package.json

Add sample worklows for CI/CD
Ref: #59 
---

Wrpd ci 59

---

.github/workflows/create-release.yml.NOT_IN_USE
.github/workflows/create-tag.yml.NOT_IN_USE
.github/workflows/service-deploy.yml.NOT_IN_USE

 merge: development into main #72 

---

wrappid.conf.json

merge: development into main

---

wrappid.conf.json

change key role to defaultUserRole
Ref: #63
---

refactor(global): :recycle: fix role key in config file

---

.github/workflows/pr-guardrails.yml

bugfix: pr gaurdrails fix

---

jest.config.js
package-lock.json
package.json
test/service.test.ts
tsconfig.json

configuration setup for jest typescript
Ref: #79
---

feat(global): jest configuration setup

---

.github/workflows/service-deploy.yml.NOT_IN_USE

Add REMOTE_PATH_OF_PROJECT_DEPLOYMENT_PATH key
#81 
---

ci(config): 🔧 update ci config for deploy

---

src/server.ts

error handling using try catch a block
Ref: #84
---

feat(global): :zap: error handling

---

src/server.ts

fix function nameing coreApp to app
Ref: #84
---

fix(global): :bug: fix function nameing coreApp to app

---

.husky/commit-msg
.husky/pre-commit
package-lock.json
package.json

update author key, enable local branch rules, update package-lock.json
#90
---

bugfix: update author key, enable local branch rules

---

jest.config.js
test/businessAllEntity.test.ts
test/businessCountEntity.test.ts
test/businessIndividualEntity.test.ts
test/businessTablesAttributesDatabaseTable.test.ts
test/businessTablesDatabase.test.ts
test/dataModelId.test.ts
test/entities.test.ts
test/formSchemaFormID.test.ts
test/noauthBusinessAllEntity.test.ts
test/noauthBusinessColumnsEntity.test.ts
test/noauthFormSchemaFormID.test.ts
test/service.test.ts
test/settingMeta.test.ts

enhancement : added test cases for service-core API 

---

src/swagger-output.json

enhancement: update swagger json

---

wrappid.conf.json

wrappid.conf json file whasapp default key add
Ref: #99
---

fix(global): :bug: wrappid.conf json file whasapp default key add

---

ATTRIBUTIONS.md
package-lock.json
package.json
scripts/attributions.gen.js

add script file to generate attribution, update scripts in package.json
Ref: #104

feat(utils): :memo: add script to generate attribution

---

test/businessAllEntity.test.ts

…tion for unauthorized access test case
added a random string generator function for unauthorized access test case
Ref: #69
---

enhancement: added a random string generator function for unauthorized access test case

---

test/businessCountEntity.test.ts
test/businessIndividualEntity.test.ts
test/businessTablesAttributesDatabaseTable.test.ts
test/businessTablesDatabase.test.ts
test/dataModelId.test.ts
test/entities.test.ts
test/formSchemaFormID.test.ts
test/noauthBusinessAllEntity.test.ts
test/noauthBusinessColumnsEntity.test.ts
test/noauthFormSchemaFormID.test.ts
test/settingMeta.test.ts

modified the test cases of service core
Ref: #69
---

enhancement: modified the test cases of service-core

---

jest.config.js
test/businessAllEntity.test.ts
test/businessCountEntity.test.ts
test/businessIndividualEntity.test.ts
test/businessTablesAttributesDatabaseTable.test.ts
test/businessTablesDatabase.test.ts
test/dataModelId.test.ts
test/entities.test.ts
test/formSchemaFormID.test.ts
test/noauthBusinessAllEntity.test.ts
test/noauthBusinessColumnsEntity.test.ts
test/noauthFormSchemaFormID.test.ts
test/settingMeta.test.ts

enhancement: service-core API test case fixing

---

package-lock.json
package.json
src/server.ts

swagger json automate versioning and supertest version change
Ref: #119
---

feat(global): :zap: swagger json automate versioning

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

to help contributors when they are raising an issue
ref: #124
There is a need for an ISSUE_TEMPLATE, so adding such a template helps the user or contributor when they are raising an issue. So I add ISSUE_TEMPLATE in this repository.
---

docs(global): :memo: adding ISSUE_TEMPLATE

---

src/registry/Routes.Registry.ts

unable to read local module routes registry
Ref: #128
---

fix(core): :bug: unable to read local module routes registry
